name: GCP App Engine Deployment
on:
  push:
    branches:
      - main jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set Google Cloud Project ID
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
---
    steps:
     - name: Create App Engine on GCP
        run: gcloud app create --region=us-east4
      - name: Clone GitHub Repo
        uses: actions/checkout@v2
      - name: Deploy App Engine to GCP
        run: gcloud app deploy app.yaml --quiet
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
