name: GCP App Engine Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set Google Cloud Project ID
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
          
      - name: Authenticate with Google Cloud
        run: gcloud auth activate-service-account --key-file=gcp-demo-project-415805-8e27a3cd1078.json
      - name: Create App Engine on GCP
        run: gcloud app create --region=us-central

      - name: Clone GitHub Repo
        uses: actions/checkout@v2

      - name: Deploy App Engine to GCP
        run: gcloud app deploy app.yaml --quiet
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
